package PlacementLog.UI;

import Placementlog.Core.ApplicationLoader;
import Placementlog.Core.OverviewControl;
import Placementlog.UI.TabPanel;
import java.awt.BorderLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;
import placementlog.Core.Types.Entry;

/**
 * The application's main frame.
 */
public class PlacementLogView extends FrameView implements WindowListener {

    private OverviewControl ovc = new OverviewControl();
    private DefaultMutableTreeNode rootNode;
    private ArrayList<DefaultMutableTreeNode> monthNodes = new ArrayList<DefaultMutableTreeNode>();
    private ArrayList<DefaultMutableTreeNode> nodes = new ArrayList<DefaultMutableTreeNode>();
    private ArrayList<Entry> entries = new ArrayList<Entry>();
    private DefaultTreeModel treeModel;
    
    private JTree tree;
    private JTabbedPane jtView;
    
    public PlacementLogView(SingleFrameApplication app) {
        super(app);
        initComponents();
        buildMonthList();
        this.getFrame().addWindowListener(this);
        nodes = ApplicationLoader.load();
        rootNode = new DefaultMutableTreeNode("Entries");
        treeModel = new DefaultTreeModel(rootNode);
        tree = new JTree(treeModel);
        tree.setEditable(true);
        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tree.setShowsRootHandles(true);
        tree.setSize(239, 508);
        tree.setBounds(0, 0, 239, 508);
        jtView = new JTabbedPane();
        bodyPanel.setLayout(new BorderLayout());
        bodyPanel.add("West",tree);
        bodyPanel.add("Center",jtView);
    }
    
    private void buildMonthList() {
        monthNodes.add(new DefaultMutableTreeNode("January"));
        monthNodes.add(new DefaultMutableTreeNode("Febuary"));
        monthNodes.add(new DefaultMutableTreeNode("March"));
        monthNodes.add(new DefaultMutableTreeNode("April"));
        monthNodes.add(new DefaultMutableTreeNode("May"));
        monthNodes.add(new DefaultMutableTreeNode("June"));
        monthNodes.add(new DefaultMutableTreeNode("July"));
        monthNodes.add(new DefaultMutableTreeNode("August"));
        monthNodes.add(new DefaultMutableTreeNode("September"));
        monthNodes.add(new DefaultMutableTreeNode("October"));
        monthNodes.add(new DefaultMutableTreeNode("November"));
        monthNodes.add(new DefaultMutableTreeNode("December"));
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = PlacementLogApp.getApplication().getMainFrame();
            aboutBox = new PlacementLogAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        PlacementLogApp.getApplication().show(aboutBox);
    }
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAddNew = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnOrderByDate = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setName("jToolBar1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(PlacementLog.UI.PlacementLogApp.class).getContext().getResourceMap(PlacementLogView.class);
        btnAddNew.setIcon(resourceMap.getIcon("btnAddNew.icon")); // NOI18N
        btnAddNew.setText(resourceMap.getString("btnAddNew.text")); // NOI18N
        btnAddNew.setFocusable(false);
        btnAddNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddNew.setName("btnAddNew"); // NOI18N
        btnAddNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddNew);

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jToolBar1.add(jSeparator2);

        btnOrderByDate.setText(resourceMap.getString("btnOrderByDate.text")); // NOI18N
        btnOrderByDate.setFocusable(false);
        btnOrderByDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrderByDate.setName("btnOrderByDate"); // NOI18N
        btnOrderByDate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrderByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderByDateActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOrderByDate);

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setName("jButton5"); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        bodyPanel.setName("bodyPanel"); // NOI18N

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(PlacementLog.UI.PlacementLogApp.class).getContext().getActionMap(PlacementLogView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
    String df = DateFormat.getDateInstance().format(new Date());
    Entry e = new Entry();
    jtView.add(df, new TabPanel(e));
    ovc.addObject(df, tree, rootNode, treeModel);
    entries.add(e);
}//GEN-LAST:event_btnAddNewActionPerformed

private void btnOrderByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderByDateActionPerformed
    ovc.orderByDate(tree, nodes);
}//GEN-LAST:event_btnOrderByDateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnOrderByDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;

    public void windowOpened(WindowEvent e) {
        
    }

    public void windowClosing(WindowEvent e) {
        FileOutputStream fos = null;
        ObjectOutputStream out = null;
        // TODO if file exists validation
        try{
            fos = new FileOutputStream("savefile");
            out = new ObjectOutputStream(fos);
            out.writeObject(entries);
            out.close();
            System.out.println("Success"); // Let us know we've reached the sequence
            
        } catch (IOException ex){
            ex.printStackTrace(); // ignore warning
        }
    }

    public void windowClosed(WindowEvent e) {
        
                  FileOutputStream fos = null;
        ObjectOutputStream out = null;
        // TODO if file exists validation
        try{
            fos = new FileOutputStream("savefile");
            out = new ObjectOutputStream(fos);
            out.writeObject(entries);
            out.close();
            System.out.println("Success"); // Let us know we've reached the sequence
            
        } catch (IOException ex){
            ex.printStackTrace(); // ignore warning
        }  
    }

    public void windowIconified(WindowEvent e) {
        
    }

    public void windowDeiconified(WindowEvent e) {
        
    }

    public void windowActivated(WindowEvent e) {
        
    }

    public void windowDeactivated(WindowEvent e) {
        
    }
}
